on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  push:

jobs:
  update:
    name: Daily update from the Google Spreadsheet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Get snapshot from GSheet
        run: python scripts/get_snapshot.py

      - name: Update Git repository
        run: git add data/ && git commit -m "Auto update $(date +'%Y-%m-%d')" && git push origin ${GITHUB_REF_NAME}
